project_id = "pbrrfxgcksptloiwshiy"

[auth]
enabled = true

[functions.chat]
verify_jwt = false

[functions.chat-demo]
verify_jwt = false

[functions.market-research]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false
